#!/bin/env bash

#SBATCH -J my_array
#SBATCH -N 1
#SBATCH --mem=9GB
#SBATCH --time=3:00:00
#SBATCH --export=none
#SBATCH --output=run_%a.out
#SBATCH --error=run_%a.err
#SBATCH --array=1-150
 
module load R/4.3.1

Rscript ddis_batchrun.R $SLURM_ARRAY_TASK_ID
